package com.mykovol.takeandcharge;

import com.codename1.io.Log;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.mykovol.takeandcharge.form.LoginForm;
import com.mykovol.takeandcharge.form.MapForm;
import com.mykovol.takeandcharge.form.SplashScreen;
import org.littlemonkey.connectivity.Connectivity;

import java.io.IOException;
import java.util.Hashtable;

import static com.codename1.ui.CN.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class TakeAndChargeMain {

    private Form current;
    private Resources baseTheme;


    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        UIManager.initFirstTheme("/theme");
        try {
            baseTheme = Resources.openLayered("/baseTheme");
        } catch (IOException e) {
            Log.e(e);
        }

        Toolbar.setGlobalToolbar(true);
        if (!isTablet()) {
            Toolbar.setOnTopSideMenu(true);
        }
        Dialog.setDefaultBlurBackgroundRadius(10);


//        Label.setDefaultGap(convertToPixels(2));
        // only portrait mode
        Display.getInstance().lockOrientation(true);
        Display.getInstance().setEnableAsyncStackTraces(true);

        // Pro only feature
        Log.bindCrashProtection(true);
        loadLocalization();

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            if (!Connectivity.isConnected()) {
                Dialog.show("No Internet connection", "Please check your Internet connection and try again", "OK", null);
            } else {
                Dialog.show("Connection Error",
                        "Error when connecting to " + err.getConnectionRequest().getUrl(),
                        "OK", null);
            }
        });
    }

    private void loadLocalization() {
        String local = L10NManager.getInstance().getLanguage();
        Hashtable<String, String> localizationBundle = baseTheme.getL10N("prime", local);
        UIManager.getInstance().setBundle(localizationBundle);
    }

    public void start() {
        MapForm.checkAndEnableGps();
        if (current != null) {
            current.show();
            return;
        }
        new SplashScreen().show();
//        MapForm.get().show();
//        new LoginForm(MapForm.get()).show();
//        new LoginForm().show();

    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
        MapForm.get().disableGps();
    }

    public void destroy() {
    }

}
