package com.mykovol.takeandcharge;

import com.codename1.components.ToastBar;
import com.codename1.io.Log;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Toolbar;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.util.StringUtil;
import com.mykovol.takeandcharge.form.MainForm;
import com.mykovol.takeandcharge.form.SplashScreen;
import com.mykovol.takeandcharge.tools.InfinityProgressBlocking;
import com.mykovol.takeandcharge.tools.MainGifLoader;
import org.littlemonkey.connectivity.Connectivity;

import java.io.IOException;
import java.util.Hashtable;
import java.util.List;

import static com.codename1.ui.CN.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class TakeAndChargeMain {

    private Form current;
    private Resources baseTheme;


    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        UIManager.initFirstTheme("/theme");
        try {
            baseTheme = Resources.openLayered("/baseTheme");
        } catch (IOException e) {
            Log.e(e);
        }

        Toolbar.setGlobalToolbar(false);
//        Toolbar.setOnTopSideMenu(false);
        Toolbar.setOnTopSideMenu(true);

        Dialog.setDefaultBlurBackgroundRadius(10);
        Display.getInstance().setProperty("BrowserComponent.useWKWebView", "true");
        Display.getInstance().setProperty("syncNativeCookies", "true");

//        Label.setDefaultGap(convertToPixels(2));
        // only portrait mode
        Display.getInstance().lockOrientation(true);
        Display.getInstance().setEnableAsyncStackTraces(true);

        // Pro only feature
        Log.bindCrashProtection(false);
        loadLocalization();

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
//            Log.sendLogAsync();
            String errorMsg = "unknown error";
            if (!Connectivity.isConnected()) {
                errorMsg = "No Internet connection";
            } else {
                if (err.getResponseCode() == 0) {
                    errorMsg = "No connection with server. Please try again latter";
                } else
                    errorMsg = err.getResponseCode() + err.getError().toString() + " while connecting to " + err.getConnectionRequest().getUrl();
//                    Dialog.show("Connection Error " + err.getResponseCode(),
//                            err.getError() + " while connecting to " + err.getConnectionRequest().getUrl(),
//                            "OK", null);
            }
            Log.p("Network error:" + errorMsg);
            InfinityProgressBlocking.stop();
            MainGifLoader.get().stop();
            if (Display.getInstance().getCurrent().equals(MainForm.get())) {
                MainForm.get().showError(errorMsg, 500);
            } else {
                ToastBar.showErrorMessage(errorMsg);
            }
        });
    }

    private void loadLocalization() {
//        String local = L10NManager.getInstance().getLanguage();
        String local = "uk";
        Hashtable<String, String> localizationBundle = baseTheme.getL10N("prime", local.toLowerCase());
        UIManager.getInstance().setBundle(localizationBundle);
    }

    public void start() {
        String arg = getProperty("AppArg", null);
        if (arg != null) {
            if (arg.contains("//")) {
                List<String> strs = StringUtil.tokenize(arg, "/");
                arg = strs.get(strs.size() - 1);
                while (arg.startsWith("/")) {
                    arg = arg.substring(1);
                }
            }
            Log.p("App arg - " + arg);
        }

        if (current != null) {
            try {
                if (current instanceof SplashScreen) {
                    MainForm.get().show();
                } else {
                    current.show();
                }
            } catch (Exception e) {
                MainForm.get().show();
            }
        } else {
//            new ImageForm().show();
            new SplashScreen().show();
//            MainForm.get().show();
//            new WalkthruForm().show();
        }
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
        MainForm.suspend();
    }

    public void destroy() {
    }

}
