package com.mykovol.takeandcharge;

import com.codename1.components.ToastBar;
import com.codename1.io.Log;
import com.codename1.l10n.L10NManager;
import com.codename1.ui.*;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.mykovol.takeandcharge.form.MainForm;
import com.mykovol.takeandcharge.form.SplashScreen;
import com.mykovol.takeandcharge.tools.FabProgress;
import com.mykovol.takeandcharge.tools.MainGifLoader;
import org.littlemonkey.connectivity.Connectivity;

import java.io.IOException;
import java.util.Hashtable;

import static com.codename1.ui.CN.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class TakeAndChargeMain {

    private Form current;
    private Resources baseTheme;


    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        UIManager.initFirstTheme("/theme");
        try {
            baseTheme = Resources.openLayered("/baseTheme");
        } catch (IOException e) {
            Log.e(e);
        }

        Toolbar.setGlobalToolbar(false);
//        Toolbar.setOnTopSideMenu(false);
        if (!isTablet()) {
            Toolbar.setOnTopSideMenu(true);
        }
        Dialog.setDefaultBlurBackgroundRadius(10);
        Display.getInstance().setProperty("BrowserComponent.useWKWebView", "true");

//        Label.setDefaultGap(convertToPixels(2));
        // only portrait mode
        Display.getInstance().lockOrientation(true);
        Display.getInstance().setEnableAsyncStackTraces(true);

        // Pro only feature
        Log.bindCrashProtection(true);
        loadLocalization();

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            String errorMsg = "unknown error";
            if (!Connectivity.isConnected()) {
                errorMsg = "No Internet connection";
            } else {
                if (err.getResponseCode() == 0) {
                    errorMsg = "No connection with server. Please try latter";
                } else
                    errorMsg = err.getResponseCode() + err.getError().toString() + " while connecting to " + err.getConnectionRequest().getUrl();
//                    Dialog.show("Connection Error " + err.getResponseCode(),
//                            err.getError() + " while connecting to " + err.getConnectionRequest().getUrl(),
//                            "OK", null);
            }
//            if (!Display.getInstance().getCurrent().equals(MainForm.get())) {
//                MainForm.get().show();
//            }
            ToastBar.showErrorMessage(errorMsg);
//            MainForm.get().showErrorDraggablePanel(errorMsg);
            FabProgress.stop();
            MainGifLoader.get().stop();
        });
    }

    private void loadLocalization() {
        String local = L10NManager.getInstance().getLanguage();
//        String local = "ua";
        Hashtable<String, String> localizationBundle = baseTheme.getL10N("prime", local.toLowerCase());
        UIManager.getInstance().setBundle(localizationBundle);
    }

    public void start() {
        if (current != null) {
            current.show();
        } else {
            new SplashScreen().show();
//            MainForm.get().show();
//            new RegisterMobileNumberStep1().show();
        }
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
        MainForm.get().suspend();
    }

    public void destroy() {
    }

}
